version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  versioning-strategy: increase
  ignore:
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.3
    - 5.1.0
    - 5.1.1
  - dependency-name: react-test-renderer
    versions:
    - 17.0.1
  - dependency-name: "@dhis2/cli-utils-cypress"
    versions:
    - 5.1.0
    - 5.1.1
    - 6.0.0
    - 7.0.0
  - dependency-name: "@dhis2/cli-app-scripts"
    versions:
    - 5.5.1
    - 5.5.2
    - 5.6.0
    - 5.7.0
    - 5.7.1
    - 5.7.2
    - 5.7.3
    - 5.7.4
  - dependency-name: "@dhis2/cli-style"
    versions:
    - 7.3.0
  - dependency-name: final-form
    versions:
    - 4.20.1
