language: node_js
node_js:
- '6'
cache:
  yarn: true
   directories:
    - node_modules
script:
- npm run build
- '[[ -z $TRAVIS_TAG ]] || mvn clean deploy --settings settings.xml'
env:
  global:
  - secure: WjwaDRWXcTCK4/OoQyGBM2A+zd1bh1sdqgJh3JHnXewSiUceYnObCtMCEQUERpIT2y8iya65grQMvVJqSGDn4JaeieD3QXqgZF3Nf0Rr2qKKAu1momU7BMmTN2OypEmI9+BRXH6FZ6YUl3p+C8oSU7aXtX+swjVNSwmNICYPqv7J0kJWUfxN2016ILH9BdOeKoLlj/Y56MJuJjQEJibgcKrc2fec1/N+qbPzuLJasvdFPcK/oo6rvtp5cLXG8IUcojeVOXWi8uwNlUk2Q4jLcGlsXXhVNpg7OrQz0nNXjfM2CFTgpIXsRhu3BhddqKpmHffYsxszaCIUEvW5+2csDWGXkqEQJVEGqsZwRdGwwMRT3WIj9u0gzBtIKYPJggjgqF9WMSZoHP3KFf/DEVNHGiKkcE50QvlZW2UOVElG9NSUAKEWN3vAKSiuu1Bt8pEwETvKBYBWORhqWeYhlg7SkjVDKWHBwCEZt3MXlGaNcqvgxX0JkWgkMGq4kLKyuJVc9VeZt4jNqtxe6nW6FwXcFaqH57PEtRpCJc331YGRyt7xnPVfCoEiMi9N6lOCyqTbVqpPYU7sZEipQyrtj5FXCioTL4WMJyhrw+0ww/KLwt3iS9oBf0Yshh7ibsjJDpHIppuHH9rmc3QsgtVd5MTvOU8V7raULJQ7PYPkHJOu8zw=
  - secure: UnFItYCdT1plm6lSSxURnRrH2RDu8EpowNCNLSCb5h6rGijv6EFTT38gv5V5YZXBq0eKfbY4zqGyLqVQPfE+ij0TF/Q5dBrNbO7dkr34LW8kgUUnWcLGxJe647HpMON1jq+326Bpoy8jDvbnm2otcW7jhi6DVt5JaCeGUnN3L+yktuY9XHgt+W9nOEpMHqgtxQvRM39SUcDmlgGpmCIeAfzagjviy9BjooeI0mwurUL9G6GWrPhPHb5oRuCU/gSdFMChwolJOfCWzu91zFsYtdoZiqOTSiFfsi2l4jrgVhFLuRDAAJRnvSiBTaxvwYC85i+Ktc22xhS/Ea03IzxplWRP7foW4AVMeZSZSYR6ycf1rL+8RNQYsIi3dN0b2oRNMyr40d7lpI1e4AhRW73AWYSCRqxvsc87+XGwcqEtKpepkGGgOzC8uV4jg3HQPii8zxdVHsgV1aM7Iawi3BEgu41YXAk27EHRyDblwqM68yWO16S88IrRe9BhICsvhorZ6MubTw8kIPDjZTQf77YlyEA/QCpI3NcJW7X3vkcyJZ4FK7qQaVQGtkuJp9AlZzSNRU8v5clJIkeI2tfOgIoP9XQzQESMRy7dN45vLsJI1+d1mgsnKLV6jTkzeFHY6Kjali94+Y7EP+JLESISCEYPi04T5ljxYc1J88L7EQdpxrU=
