language: node_js
node_js:
- '6'
before_install:
- git clone -b travis `git config --get remote.origin.url` target/travis
branches:
  except:
  - travis
cache:
  yarn: true
script: 
    - npm run build
    - '[[ -z $TRAVIS_TAG ]] || mvn clean deploy --settings settings.xml'
env:
  global:
  - secure: QP2DmVuzFurIcAAWzn0AIFZyCeHHPiAUv5wj9VkILlFdaLwZoT6DvlYMtBf1+2Jtd1yGLAoolkx2+bLevvF8FlI6OXkG4eUJaE9Th4hyfJXWVy0Uk1y5PCpqf3bh6kbZZ470JY3DPZtW7dPrxjOOsWWo5pjk94j2GtmFArYpoKEw8ECx3NwPQmvxio3OEir8QJRW4UmhkxnLt94TrhvP435s6hK8V+cQG4f2GkdbDLjs3TKWXuYg85xfVlra075e0i3jFRDBvyuDY+a52iUO8FnoQtoLk3HBZw3YuxzSFggAEVpXsEFDOHCqItPHt5y0BwPmHRuU7b8grLpi/qJHFDqT8GBCFhi4LTu2jRw/mKiGper2LMxjmdNeB6SP/hh/bdYMWH+YFSfw0x0RykGW5KlIOnw9kwFnfAWvN4EiEAr0zzScvXszuyjQ9cGV6/CdeAcy5a8rX6FbG7fwQDSXbLMZz0gHOTloXsqR4IyO9ZMnb1voi+srRfg2+Cu7FXhBsBSpB+kw7zejKWll4/WuWN3kZGWaAsBvKuss5JEEm7uLJPHuDcvBeMfwclSB+i5STkbaYtwKesRNj+0y7s/bnCgfsZ0aAlRwelkIItKC89NIReR0W9OzkxyG1J/JB0+gb7FY6wFHBiplpChsmIeDbdMudmjXHOPj9iXU78OWiBo=
  - secure: tyMKlhlJi0+3b4bfAYFar+SYtYyuLUWUQ/b/X1Bl4hGvDD2KI29Ch6jo2IZe2uKtLKiCFxOtQTllNDkwzQsq3CFVErpxur7wN8xRMx8+Scs5wZqSgIh7ZzszxQeWHmaQbqMnWpOKpcmFHx4rIKTHHf8S/YynLaUqRWCG4Wwqb61Ic55pADtIPsYiBFPs3UfGW9kGgU2jN020E3TjO52X24Mboujf2tsUK0YkH1hVQ2vmycHLwSBwOkNTmR/Y5QGJCw1z3FhgWBbhqGmd5hwHxuRdtTwFA9xee6UM/e9ITyQ7x1PU2r4ovz4/AvEckWTCj2eVBv8DwFO8m9yi49o5zw4Ubg0RQrA0iIMoSRlcSEOZ6mwITAFzI/CWL3zTYWdA2d7Rl+0Vz5rka/UuShtZvFTm+Up4lR6BPH+ib6FRMee42TJeM7dajIvEp5OAeCq/E2sENtg1Bb5PzbfoYgctjYnlLpOWjoByM9x5AECK5NqaG1OxwL+3gSF0SB61tUsHI5+6cmiVvvwFD83zBGDI+kBeolRMRySSYoGFpS2CEMZYuWpFWj69yMP65hYllNDuMHURwsEJQrSKou2SfhtiL+wEZbrNiTRObs37gyaPY7atJVW4/qlGixDGAwWkVHRteu0/85Xwv4AuSIk3fsLoo1DthKySI/YgMFjM7VR4WDU=
