language: node_js
node_js:
- '6'
cache:
  yarn: true
script:
- npm run build
after_sucess: mvn clean deploy --settings settings.xml
env:
  global:
  - secure: 0dUVyi+/5iCFos6oBOgwXyfx2uvX+thQNFJKhJjYFrPyJqGSuBg+eHFkOfmpKRrfJlV/CS+YvBTHD4K/Pgm7qerpbFHxJR2ri/Wzzr44+qc6h3df8t2AUkCwHQ4nO1WeVF/QQv4aIO7AovIn/o1+mj73PjHbQ7txAaMKhQtRCLuArHtW9RpE8IWmcUWMyhg2M7y3iuT0pzG3p3eA83w76SefyPxnuYGXrGFglf1zpF1BB7v67hC9WPIFFFYB/i2MpTn67gnQW4V9otIzYwDNPXUid5vKvVTRmfljpauC+JX5Z1q5pZ6tF6AFsfN1kwz2Q2JKyTJN0wVBKafTubaM5KVG9yNKu1Mq98AeBsYOAV3vWdgf/fnPgZsLshZC6ih8JuGWwA5Igen543ju/OPPx8zDKshrTSztCsCdEwClGjnIEOVH+vsjLfyM416C0pek+LV07z3uWAO2eykTJ/he8ItaOhpVPFru4mPNHcz72kO/wuVteWFoEiOA3ZN0RGuatBlxFmoAmCeA13hwnt2JhjHMATyb1UYlQo7tajyi6QcEc0f0w54wnlHwi3bo9lWczrunnxBf7KiKZ8IIfLInWCzZWzxxB7/GNCY+YbyBpZINDmKYVAfLHT25Lt5MX/EG5pmXlKg8b11tEHs/orj8HXkVrl7i3FSuBEu7a5rSDYE=
  - secure: czIiiGIAS7vwlD/xR4y8Qc9HFx81Lo+4XhtbF/RSwHCs3JNvns1QnVWiwXzNRvDt4VSHCYOStz1ftr39+pLwQetrnk8CPEIy8BgTKOqZj/1Z5Gp1tFOaH0TrUyYVtyL//3hLL6sPT75DWZ96payDMhJ4GG2IWR1Mxl/7v/0r1aa4ISjjKrE2JLfWF6TDYinfR1tbOkS1dLis/hwxmpgrRKR8jNFKqc2WsjERzDDLMixqjCzfLfF1sR1rZPfOiDFbTQbGe9/TxPrqeGCAVmnTQItn/Qh0mtyPbScY1BXlj8Ynv5G3gPyOyITCNNGY53xFAWHtVvLtQnqJpk8s5wcAn4TrwTXkGbxe6vSA+45khFlaOt05ww1cj+vkmORTXvfoAwYQQFNs0mgBzXjU/i4ix1GWqlZYSreCj0Cr1otyrd7Xkt5H4wLWeaw4kP1eEmCotbZPDck4xZ+0Kx9ufi7wemJJ2wUu2kIDI1tQMAHdDnTcz9oiYpog23jswGgaClessjjS6mw+t9GkyYQpKHrYrCPqBTc0W8+cp7551YqMDTuct9qMqA21r+ihVpdCwJCXzRacnMRLWZnKk/Jq657U1EA8c2tjZSUSH5EkWIiw5If998+izAGbC2hl8ddjTHutF7DWWnAdzXr1cxdKdxdayEPh3FI9RyDyYmMxpX7/aPI=
