name: 'dhis2: verify (app)'

on: push

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    GH_TOKEN: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
    APPHUB_TOKEN: ${{secrets.DHIS2_BOT_APPHUB_TOKEN}}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - name: Build
              run: yarn build

            - uses: actions/upload-artifact@v2
              with:
                  name: app-build
                  path: |
                      **/build
                      !**/node_modules
                  retention-days: 1

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - name: Generate translations
              run: yarn d2-app-scripts i18n generate

            - name: Lint
              run: yarn lint

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile
            - name: Generate translations
              run: yarn d2-app-scripts i18n generate
            - name: Test
              run: yarn test

    e2e:
        runs-on: ubuntu-latest
        if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"
        strategy:
            fail-fast: false
            matrix:
                containers: [1, 2, 3, 4]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: End-to-End tests
              uses: cypress-io/github-action@v2
              with:
                  start: yarn start:nobrowser
                  wait-on: 'http://localhost:3000'
                  wait-on-timeout: 300
                  record: true
                  parallel: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  CYPRESS_dhis2BaseUrl: https://debug.dhis2.org/dev
                  CYPRESS_dhis2ApiVersion: 37
                  CYPRESS_networkMode: stub

    release:
        runs-on: ubuntu-latest
        needs: [build, lint, test, e2e]
        if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{env.GH_TOKEN}}

            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - uses: actions/download-artifact@v2
              with:
                  name: app-build

            # ensure that d2-app-scripts is available
            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - uses: dhis2/action-semantic-release@master
              with:
                  publish-apphub: true
                  publish-github: true
                  github-token: ${{ env.GH_TOKEN }}
                  apphub-token: ${{ env.APPHUB_TOKEN }}
                  debug: true

            - uses: dhis2/deploy-build@master
              with:
                  build-dir: build/app
                  github-token: ${{ env.GH_TOKEN }}
